### ISSUE TITLE
Add a Display Name form label

### ISSUE THREAD

**Issue by davidlav** [MobiFlight/HubHop-Website#41]
Just went to create an account via Google, and the screen below popped up with my full real name auto-filled.

![image](https://user-images.githubusercontent.com/18689323/131550625-9bfff4ce-ce55-4b8f-b6b3-30db41ae7588.png)

I assumed it was asking me to provide a username, but since the text field was already auto-populated, I didn't see the placeholder text `Display Name` until I deleted my own name.

Please either 1) add a field label that says `Display Name` somewhere on the form itself, outside of the input field, or 2) keep the placeholder text but don't auto-populate it so that the placeholder text is actually visible from the beginning.

Thanks

**Comment by rofl-er** [comment]
@Mobiflight Could you please look into the Azure settings? Thanks!

**Comment by rofl-er** [comment]
@MobiFlight-Admin Is that an open issue or cant this issue be closed?
