### ISSUE TITLE
Add a safety category to the C172

### ISSUE THREAD

**Issue by danecreekphotography** [MobiFlight/HubHop-Website#42]
The C172 plane is missing a `Safety` category for events. This is needed to align with the in-sim event groupings in the Input Events panel.

These two events should be moved under it once created:

https://hubhop.mobiflight.com/#/presetview/3e54f272-8b43-44a5-933b-149c20c1315f
https://hubhop.mobiflight.com/#/presetview/04a52e54-136c-4728-aa6a-40cad3adf23a

**Comment by rofl-er** [comment]
@danecreekphotography

You can add your own system category when adding the preset to Hubhop. Just make sure to click the orange little "+" and the select field will turn into an input field where you can type whatever you wish:
![image](https://user-images.githubusercontent.com/43043841/131784402-941fc9aa-401d-428a-b9da-aab8b6983101.png)

You can edit already submitted presets by toggling to "Edit" and change the system category yourself like shown here:
![image](https://user-images.githubusercontent.com/43043841/131784284-6ef0c623-8956-41b0-8062-fa9ae9691feb.png)

**Comment by danecreekphotography** [comment]
😲

**Comment by danecreekphotography** [comment]
I've updated the two entries to use "Safety".
