### ISSUE TITLE
Import events from events.txt format files 

### ISSUE THREAD

**Issue by JaimeLeon2** [MobiFlight/HubHop-Website#43]
Currently the only way to add events to Hubhop is to input them one by one through the UI. That is fine for adding a few events, but not if we want to import a large number. 

It would be very good to have the alternative to do "bulk" imports from text files in the events.txt format. Filter data like vendor and airplane could be pre-selected before the import. Group markers in the text file can be used to select the systems filter.

This could potentially allow MF to import the events from outside apps that use the MF Wasm, which would probably use the events.user.txt file to add their own custom or events not found in MF.

**Comment by rofl-er** [comment]
Bulk-upload was added as a workaround. Import functions will come at a later stage.
