### ISSUE TITLE
Hubhop asks to relogin too often

### ISSUE THREAD

**Issue by JaimeLeon2** [MobiFlight/HubHop-Website#45]
Hubhop will log you off even when checking the "keep me logged in box" when logging in.
Suggest the log in cookie have a life of at least 48 hours and the time to expire should be counted from the last access, not from the last log in.

**Comment by rofl-er** [comment]
This is true and I will look into it.

**Comment by rofl-er** [comment]
It should be resolved. Please open a new issue if the situation persists. 

Thank you!
