### ISSUE TITLE
Minimize response time by not reloading the database 

### ISSUE THREAD

**Issue by JaimeLeon2** [MobiFlight/HubHop-Website#47]
Currently the database of events is reloaded every time the list view page is accessed, making the list view page very slow to load, especially when the majority of times, no changes are made. Reloading the database is probably not necessary, unless a change has been made.

Maybe the Javascript can decide if a reload is necessary.

In order to make changes, the user needs to press the "Add Event" button in list view, or the "Edit" button in detail view, so only if those two actions are done Hubhop would need to reload the database.

**Comment by rofl-er** [comment]
@JaimeLeon2 I have improved it a little for you as a workaround. Please refer to our hubhop channel on discord.
