### ISSUE TITLE
Hubhop is slow in recognizing if login is required. 

### ISSUE THREAD

**Issue by JaimeLeon2** [MobiFlight/HubHop-Website#48]
When opening Hubhop it feels quite slow in deciding if login is required. A pop up window opens, just to disappear several seconds later.

Streamlining will improve the user experience. If the user is pre-registered and has logged in before it should be very fast, IMHO.

**Comment by rofl-er** [comment]
I have not had that experience in the past. The pop up window is part of Azures MSAL token acquisition function and cant be removed.

@JaimeLeon2  Can you do me a favor and try to ping hubhop.mobiflight.com and check if your connection is bad? @MobiFlight-Admin  I have the suspicion that that might be an Azure Server Location issue.

**Comment by rofl-er** [comment]
@JaimeLeon2 I have improved it a little for you as a workaround. Please refer to our hubhop channel on discord.

**Comment by rofl-er** [comment]
As I have not heard anything back, I will close this issue. Please feel free to reopen the issue.
