### ISSUE TITLE
add "Input (Potentiometer)" class to form preselect classes

### ISSUE THREAD

**Issue by tigert** [MobiFlight/HubHop-Website#49]
So potentiometer events are kinda special since they do not work as preset but only in msfs2020 custom code. 

So they are useful to store and collect in hubhop, but should not be included in events.txt exports for now as they wont work, as you cannot pass a parameter to "msfs 2020 events".

We have started to add potentiometer events with "Input (Potentiometer)" -category and try to use it consistently until it can be added to the "add new event" form etc..

**Comment by rofl-er** [comment]
Done. They will be exported now but probably without function. Make sure to use describe the issue in the description box.
