### ISSUE TITLE
Filter criteria does not consider full text

### ISSUE THREAD

**Issue by JaimeLeon2** [MobiFlight/HubHop-Website#50]
For the vendor, airplane and input/output fields, the filter criteria only searches and matches the characters given, without considering the full text of the fields being read and compared to the criteria.  So searching for "A" will return "A" and also "AB" and "AC".  This is OK for the event name search, but not for the other fields where the text is taken from a drop down list, so an exact match should be enforced. 

This became evident after introducing the A320-Dev as a new airplane.  A search for A320 will list the events for the A320 and also the A320-Dev, but a search for A320-Dev only returns those for A320-Dev.

A search for "Input" returns all events marked as Input, but also returns "Input (Potentiometers)".  This is a new category we introduced for potentiometer events.

**Comment by rofl-er** [comment]
Exact text is now considered. Filters should work as described.
