### ISSUE TITLE
Add meta tags for pretty inline previews on Discord

### ISSUE THREAD

**Issue by neilenns** [MobiFlight/HubHop-Website#52]
We should add meta tags to the HubHop entry pages so when pasted into Discord it shows a pretty preview.

Example of what might work:

```html
<meta property="og:title" content="{Preset name}" />
<meta property="og:image" content="https://www.hubhop.com/img/logo-big.fd572e09.png" />
<meta property="og:type" content="website" />
<meta property="og:description" content="{description}" />
```

**Comment by rofl-er** [comment]
A fixed solution was implemented. Once migrated to Nuxt, we might have options for dynamically adding meta tags
