### ISSUE TITLE
Enhancement - Include time stamp as comment in events.txt

### ISSUE THREAD

**Issue by JaimeLeon2** [MobiFlight/HubHop-Website#55]
Currently, it is very diffictult to tell how updated events.txt is.  The time stamp on the file itself is a poor indication as it varies with the time when the file was actually downloaded.  If the file is read from the repository, the content can be even older, but the file is recorded in the PC with the time it was downloaded.

An easy solution would be to include a comment in the first line of events.txt with a time stamp of when the file was created.  Presumably, Hubhop will include all events existing on that date and time.  This would give us a clear indication of the database version and whether certain changes to the events are included or not, without having to inspect the database content.

It would be even better if Mobiflight Connector were able to read this info and display it somewhere, maybe in the Settings menu.

**Comment by rofl-er** [comment]
@MobiFlight-Admin this one is for you on API level, isn't it?

**Comment by rofl-er** [comment]
Fixed with new hubhop version
