### ISSUE TITLE
Capability to duplicate a preset

### ISSUE THREAD

**Issue by zorzini** [MobiFlight/HubHop-Website#56]
It is possible to add a "Duplicate" button to insert a new event starting from an existing one ?

Many events are very similar to each other (see FMC keyboards) and differ only in a few characters or words.

Starting with an existing event would allow for faster entry and formatting of the event content more homogeneously.

**Comment by JaimeLeon2** [comment]
I agree this function would be helpful to capture similar events. However, Hubhop should not allow duplicate names to be entered.

**Comment by zorzini** [comment]
> I agree this function would be helpful to capture similar events. However, Hubhop should not allow duplicate names to be entered.

Obviouly i mean that the "duplicate" function will be a base for a new event with the same event name root and to allow a coherent description.

Actually i copy from an existing event name and description and proceed with the appropriate modifications.

**Comment by rofl-er** [comment]
Fixed with new hubhop version
