### ISSUE TITLE
Page counter at bottom of Reported Presets page is wrong

### ISSUE THREAD

**Issue by JaimeLeon2** [MobiFlight/HubHop-Website#58]
The page counter at the bottom of the Reported Presets page shows there are 10 pages, but upon clicking on any page number, the counter immediately changes to only 2 pages.

![image](https://user-images.githubusercontent.com/86563553/150166400-2687f0cb-6b0d-48f4-8818-9988d71f741c.png)

**Comment by rofl-er** [comment]
No reports with new hubhop version
