### ISSUE TITLE
Hubhop needs quality assurance checks before accepting a new event

### ISSUE THREAD

**Issue by JaimeLeon2** [MobiFlight/HubHop-Website#62]
This is a long standing request that seems lost since Hubhop no longer maintains a list of issues at the website.

Currently Hubhop has several opportunities for improvement in the area of checking the information entered by users to new or existing events to ensure that it complies with certain standards.

This list is just a as examples, not intended to be exhaustive of all issues related to quality of input in Hubhop events.

1. No spaces or special characters should be allowed either at the beginning or at the end of event names.  Only alphanumeric characters should be allowed.
2. Vendor, Airplane and System categories should be added by authorized persons only.
3. Hubhop should enforce that only existing categories can be selected for new events.  If users require new categories they should make a request in the Hubhop-support channel.  
4. Authorized users can enter new airplane categories as new airplanes become available, e.g. ATR42-600

**Comment by JaimeLeon2** [comment]
5. I found that a user had entered code starting with ^ which is obviously a mistake and caused an exception in MFConnector.  Special characters should also not be allowed in the RPN code.

**Comment by JaimeLeon2** [comment]
6. User entered new categories in Spanish... any new category should only be allowed to Moderators.  The new categories caused the updates to Mobiflight to fail, causing an interruption to everyone until the new events were deleted from the database.

**Comment by JaimeLeon2** [comment]
A friendly reminder that this and other issues have been open for a long time.

**Comment by rofl-er** [comment]
- [ X ] No spaces or special characters should be allowed either at the beginning or at the end of event names. Only alphanumeric characters should be allowed.
- [ X ] Vendor, Airplane and System categories should be added by authorized persons only. (Vendor and Aircraft can be added by anyone. Check for special characters added.)
- [ X ] Hubhop should enforce that only existing categories can be selected for new events. If users require new categories they should make a request in the Hubhop-support channel.
- [ X ] Authorized users can enter new airplane categories as new airplanes become available, e.g. ATR42-600 (See Point 2)
- [ X ] I found that a user had entered code starting with ^ which is obviously a mistake and caused an exception in MFConnector. Special characters should also not be allowed in the RPN code. (only allow RPN Syntax to be entered in the code field)
- [ X ] User entered new categories in Spanish... any new category should only be allowed to Moderators. The new categories caused the updates to Mobiflight to fail, causing an interruption to everyone until the new events were deleted from the database. (See Point 2)
